site_name: CodeFusion Studio
copyright: Copyright &copy; 2024-2026 Analog Devices Inc. All Rights Reserved.
site_url: https://developer.analog.com/docs/codefusion-studio
site_description: CodeFusion Studio is a powerful, easy-to-use development environment for Analog Devices' microcontrollers.

theme:
  name: harmonic
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tooltips
    - content.code.copy

extra:
  version:
    provider: mike

extra_css:
  - assets/templates/pdf_overrides.css
  - assets/stylesheets/custom.css

plugins:
  - glightbox
  - material/search
  - print-site:
      enabled: !ENV [ENABLE_PDF_EXPORT, false]
      add_cover_page: true
      enumerate_headings: false
      print_page_title: CodeFusion Studio
      cover_page_template: "docs/assets/templates/cover_page.tpl"
  - mike:
      alias_type: copy


nav:
  - User Guide:
    - user-guide/index.md
    - About:
      - user-guide/about/index.md
      - Purpose: user-guide/about/purpose.md
      - Features: user-guide/about/features.md
      - Navigation: user-guide/about/navigation.md
      - Supported processors: user-guide/about/supported-processors.md
      - Supported AI model formats: user-guide/about/supported-ai-model-formats.md
      - Telemetry: user-guide/about/telemetry.md
      - Help: user-guide/about/help.md
    - Installation:
      - user-guide/installation/index.md
      - Software requirements: user-guide/installation/software-requirements.md
      - Install CFS: user-guide/installation/install-cfs.md
      - Install the VS Code extension: user-guide/installation/install-extensions.md
      - Set up CFS: user-guide/installation/set-up-cfs.md
      - Package Manager:
          - Overview: user-guide/installation/package-manager/index.md
          - Manage packages from the Command Palette: user-guide/installation/package-manager/manage-packages-command-palette.md
          - Manage packages from the command line (`cfsutil`): user-guide/installation/package-manager/manage-packages-cfsutil.md
          - Available packages: user-guide/installation/package-manager/available-packages.md
          - Install required packages: user-guide/installation/package-manager/install-required.md
          - Log in to access restricted packages: user-guide/installation/package-manager/auth.md
          - Troubleshoot package issues: user-guide/installation/package-manager/troubleshooting-package-manager.md
    - Workspace Management:
      - user-guide/workspaces/index.md
      - Create a new workspace: user-guide/workspaces/create-new-workspace.md
      - Open a workspace: user-guide/workspaces/open-workspace.md
      - Explore and open MSDK examples: user-guide/workspaces/open-and-migrate-example.md
      - Migrate a project to System Planner: user-guide/workspaces/migrate-project-to-system-planner.md
      - AI workspaces:
        - Create workspace from AI model: user-guide/workspaces/create-workspace-from-ai-model.md
        - Deploy and profile an AI model: user-guide/workspaces/deploy-and-profile-ai-model.md
      - Target-specific setup:
        - user-guide/workspaces/targets/index.md
        - TrustZone: user-guide/workspaces/targets/trustzone.md
    - System Planner:
      - user-guide/tools/index.md
      - Peripheral Allocation: user-guide/tools/peripheral-allocation.md
      - Pin Config: user-guide/tools/pin-config.md
      - Clock Config: user-guide/tools/clock-config.md
      - Memory Allocation: user-guide/tools/memory-allocation.md
      - Registers: user-guide/tools/registers.md
      - Embedded AI tools:
        - Overview: user-guide/tools/manage-ai-models.md
        - Compatibility Analyzer report: user-guide/tools/compat-report.md
        - Resource Profiling report: user-guide/tools/profiling-report.md
      - Profiling: user-guide/tools/profiling.md
      - Generate Code: user-guide/tools/generate-code.md
    - Build and Flash:
      - user-guide/build-and-flash/index.md
      - Build and flash tasks: user-guide/build-and-flash/tasks.md
      - CFS settings: user-guide/build-and-flash/cfs-settings.md
      - The CFS Terminal: user-guide/build-and-flash/cfs-terminal.md
      - Zephyr RTOS: user-guide/build-and-flash/zephyr.md
      - Troubleshooting: user-guide/build-and-flash/troubleshooting.md
    - CFS Command Line Utility:
      - user-guide/cfsutil/index.md
      - AI:
        - user-guide/cfsutil/ai/index.md
        - Backends: user-guide/cfsutil/ai/backends.md
        - Build: user-guide/cfsutil/ai/build.md
        - Clean cache: user-guide/cfsutil/ai/clean-cache.md
        - Compat: user-guide/cfsutil/ai/compat.md
        - Model management: user-guide/cfsutil/ai/model.md
        - Profile: user-guide/cfsutil/ai/profile.md
        - Workspace: user-guide/cfsutil/ai/workspace.md
      - Catalog: user-guide/cfsutil/catalog.md
      - CFS Plugins: user-guide/cfsutil/cfs-plugins.md
      - Device Tree: user-guide/cfsutil/device-tree.md
      - Docker: user-guide/cfsutil/docker.md
      - ELF Utilities: user-guide/cfsutil/elf-utilities.md
      - Generate: user-guide/cfsutil/generate.md
      - myAnalog authentication: user-guide/cfsutil/myanalog-auth.md
      - Package Manager: user-guide/cfsutil/package-manager.md
      - Plugins: user-guide/cfsutil/oclif-plugins.md
      - Port: user-guide/cfsutil/port.md
      - Project: user-guide/cfsutil/project.md
      - SoCs: user-guide/cfsutil/socs.md
      - Tasks: user-guide/cfsutil/tasks.md
      - Workspace: user-guide/cfsutil/workspace.md
    - Debugging:
      - user-guide/debugging/index.md
      - Install debug drivers:
        - user-guide/debugging/debug-drivers/index.md
        - Install Olimex JTAG drivers: user-guide/debugging/debug-drivers/install-olimex-drivers.md
        - Install Segger J-Link drivers: user-guide/debugging/debug-drivers/install-jlink-drivers.md
        - Install ICE drivers (Windows only): user-guide/debugging/debug-drivers/install-ice-drivers.md
      - Connect hardware: user-guide/debugging/connect-hardware.md
      - Debug an application: user-guide/debugging/debug-an-application.md
      - Debugging interface:  user-guide/debugging/debug-interface.md
      - Debug a multicore MSDK application: user-guide/debugging/debug-multi-core-application.md
      - Debug a SHARC-FX application: user-guide/debugging/debug-sharc-fx.md
      - Debug with SEGGER Ozone: user-guide/debugging/debug-with-ozone.md
      - Debug tools:
          - user-guide/debugging/debug-tools/index.md
          - AI Debug Assistant:
              - user-guide/debugging/debug-tools/ai-debug-assistant/index.md
              - Getting started: user-guide/debugging/debug-tools/ai-debug-assistant/getting-started.md
              - Using the AI Debug Assistant: user-guide/debugging/debug-tools/ai-debug-assistant/using-ai-debug-assistant.md
              - Tools and workflows reference: user-guide/debugging/debug-tools/ai-debug-assistant/reference.md
              - Troubleshooting: user-guide/debugging/debug-tools/ai-debug-assistant/troubleshooting.md
          - GDB Toolbox:
              - user-guide/debugging/debug-tools/gdb-toolbox/index.md
              - About the GDB Toolbox: user-guide/debugging/debug-tools/gdb-toolbox/gdb-toolbox-about.md
              - Using the GDB Toolbox: user-guide/debugging/debug-tools/gdb-toolbox/gdb-toolbox.md
              - GDB Toolbox reference: user-guide/debugging/debug-tools/gdb-toolbox/gdb-toolbox-reference.md
              - GDB Toolbox examples: user-guide/debugging/debug-tools/gdb-toolbox/gdb-toolbox-examples.md
          - Core Dump Analysis Tool:
              - user-guide/debugging/debug-tools/core-dump-analysis/index.md
              - Overview: user-guide/debugging/debug-tools/core-dump-analysis/core-dump-overview.md
              - Enable core dump support: user-guide/debugging/debug-tools/core-dump-analysis/core-dump-enable.md
              - Analyze core dumps: user-guide/debugging/debug-tools/core-dump-analysis/core-dump-analyze.md
              - Interpret core dump results: user-guide/debugging/debug-tools/core-dump-analysis/core-dump-interpret.md
          - Memory Viewer:
              - user-guide/debugging/debug-tools/memory-viewer/index.md
      - Troubleshooting: user-guide/debugging/troubleshooting.md
    - Developer Tools:
      - user-guide/developer-tools/index.md
      - ELF File Explorer: user-guide/developer-tools/elf-file-explorer.md
      - Device Tree View: user-guide/developer-tools/device-tree-view.md
      - Catalog Manager: user-guide/developer-tools/catalog-manager.md
    - Plugins:
      - user-guide/plugins/index.md
      - Plugins overview: user-guide/plugins/plugin-integration-overview.md
      - Develop plugins: user-guide/plugins/develop-plugins.md
    - Uninstalling CodeFusion Studio: user-guide/uninstall/uninstall-cfs.md
  - Tutorials:
    - tutorials/index.md
    - GDB Tutorial:
      - tutorials/gdb-tutorial/index.md
      - GDB basics: tutorials/gdb-tutorial/gdb-basics.md
      - GDB command types: tutorials/gdb-tutorial/gdb-command-types.md
      - GDB commands: tutorials/gdb-tutorial/gdb-commands.md
    - MAX32657/MAX32658 Zephyr 4.4.0:
      - tutorials/max32657-zephyr/index.md
      - Blinky: tutorials/max32657-zephyr/blinky.md
      - Low power mode: tutorials/max32657-zephyr/low-power-mode.md
  - Resources:
    - user-guide/resources/index.md
    - SDKs: user-guide/resources/sdk-resources.md
    - Security: user-guide/resources/security-resources.md
    - Third-party: user-guide/resources/third-party-resources.md
  - Release Notes:
    - release-notes/index.md
    - 2.2.1: release-notes/2.2.1.md
    - 2.2.0: release-notes/2.2.0.md
    - 2.1.0: release-notes/2.1.0.md
    - 2.0.2: release-notes/2.0.2.md
    - 2.0.1: release-notes/2.0.1.md
    - 2.0.0: release-notes/2.0.0.md
    - 1.1.0: release-notes/1.1.0.md
    - 1.0.2: release-notes/1.0.2.md
    - 1.0.0: release-notes/1.0.0.md

not_in_nav: |
  glossary.md
  index.md
  walkthrough

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - docs/glossary.md
  - pymdownx.details
  - pymdownx.superfences
