/**
 *
 * Copyright (c) 2025 Analog Devices, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

export function formatGdbOutputForMarkdown({
  gdbOutput,
}: {
  gdbOutput: string;
}): string {
  const now = new Date();
  const dateString = now.toLocaleDateString();
  const timeString = now.toLocaleTimeString();
  return `
<div align="center">

# <span style="color:#0078D4;">GDB Toolbox Report</span>

</div>

---

> **This report was automatically generated by the <span style="color:#0078D4;">GDB Toolbox</span>.**

- 🗓️ **Date:** ${dateString}
- ⏰ **Time:** ${timeString}
- 📄 **Share this report with your team or save for future reference**
- 📚 **For more details, see your debug session logs or documentation**

---

## 📝 Output

\`\`\`
${gdbOutput?.trim() || "(No output)"}
\`\`\`

---

<div align="center" style="color:#888;font-size:0.95em;">
  <em>Copyright (c); ${now.getFullYear()} Analog Devices, Inc.</em>
</div>
`;
}
