/**
 *
 * Copyright (c) 2026 Analog Devices, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 */

// AUTO-GENERATED by scripts/extract-setting-defaults.js
// Do not edit manually. Source of truth: packages/ide/package.json contributes.configuration.

export const cfsSettingDefaults: Record<string, unknown> = {
  "cfs.configureWorkspace": "No",
  "cfs.home.openAtStartup": "Yes",
  "cfs.systemPlanner.openAtStartup": "Yes",
  "cfs.sdk.path": null,
  "cfs.telemetry.enable": null,
  "cfs.telemetry.userId": "",
  "cfs.telemetry.userType": "",
  "cfs.environment": {},
  "cfs.xtensa.core": "",
  "cfs.programFile": null,
  "cfs.riscvProgramFile": null,
  "cfs.debugPath": null,
  "cfs.riscvDebugPath": null,
  "cfs.activeContext": "Workspace",
  "cfs.mcp.port": 0,
  "cfs.mcp.runOnActivation": false,
  "cfs.traceCapture.configuration": {},
  "cfs.catalogManager.checkForUpdates": true,
  "cfs.catalogManager.catalogLocation": "${userHome}/cfs/2.2.0/.catalog",
  "cfs.cmsis.root": "${userHome}/AppData/Local/Analog/Packs",
  "cfs.cmsis.pack": null,
  "cfs.cmsis.svdFile": "",
  "cfs.cfgtools.views.aiTools.showDeleteConfirmDialog": true,
  "cfs.cfgtools.views.aiTools.showNeuroweaveCodegenTimeWarning": true,
  "cfs.openocd.path": "${config:cfs.sdk.path}/Tools/openocd",
  "cfs.openocd.interface": null,
  "cfs.openocd.target": null,
  "cfs.openocd.riscvInterface": null,
  "cfs.openocd.riscvTarget": null,
  "cfs.debugger.SWD": "MAX32625PICO",
  "cfs.plugins.searchDirectories": [
    "${userHome}/cfs/plugins"
  ],
  "cfs.project.target": null,
  "cfs.project.board": "EvKit_V1",
  "cfs.project.name": "${workspaceFolderBasename}",
  "cfs.project.firmwarePlatform": "MSDK",
  "cfs.project.sdk.id": null,
  "cfs.jlink.path": null,
  "cfs.jlink.device": null,
  "cfs.ozone.executable": null,
  "cfs.toolchain.id": null,
  "cfs.toolchain.version": null,
  "cfs.toolchain.armAArch32GCC.path": "${config:cfs.sdk.path}/Tools/gcc/arm-none-eabi",
  "cfs.toolchain.riscVGCC.path": "${config:cfs.sdk.path}/Tools/gcc/riscv-none-elf",
  "cfs.tools.searchDirectories": [
    "${config:cfs.sdk.path}/Utils",
    "${config:cfs.sdk.path}/Tools",
    "${config:cfs.sdk.path}/SDK"
  ],
  "cfs.zephyr.sdk.path": "${config:cfs.sdk.path}/Tools/zephyr-sdk",
  "cfs.coreDump.binFile": "core-dump.bin",
  "cfs.coreDump.address": "0x102F0000",
  "cfs.coreDump.size": "0x10000",
  "cfs.coreDump.elfFile": "${config:cfs.programFile}",
  "cfs.coreDump.logFile": "",
  "cfs.coreDump.projectFolder": "${workspaceFolder}",
  "cfs.zephyrCoreDumpScriptsPath": "${config:cfs.sdk.path}/SDK/zephyr/zephyr/scripts/coredump",
  "cfs.coreDump.gdbServerPort": "1234",
  "cfs.sigmaStudioPlus.path": "C:/Analog Devices/SigmaStudioPlus-Rel2.4.0/"
};
