# Copyright (c) 2026 Analog Devices, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import logging
import sys
from pathlib import Path

from pydantic import TypeAdapter

from cfsai_backend_izer.exceptions import IzerError
from cfsai_backend_izer.extensions import CfsaiIzerExtensions
from cfsai_backend_izer.izer import CNNGeneratorArgs, codegen
from cfsai_types.config.verified import VerifiedBackendConfig
from cfsai_types.logging import EventType, log_event, setup_logger

logger = logging.getLogger("cfsai_backend_izer")

def _parse_input_shape(s: str) -> list[int]:
    dims = s.strip().split(',')
    try:
        res = [int(x) for x in dims]
    except Exception:
        raise
    return res

def _convert_to_cfs(
        code_path: Path, 
        report_dir: Path, 
    ) -> None:
    """
    Post process the code generated by the ai8x-synthesis tool.

    Args:
        code_path: Path to the generated code.
        report_dir: Directory to report generated file.
    """
    main_c_file = code_path / 'main.c'

    if main_c_file.exists():
        main_c_file.unlink()

    allowed_extensions = {
        '.c', '.h','.cpp', '.hpp','.cc', '.cxx', '.hxx'
    }
    for item in code_path.iterdir():
        if item.is_file() and item.suffix in allowed_extensions:
            log_event(
                logger,
                EventType.FILE,
                report_dir / item.name
            )


def _build(cfgs: VerifiedBackendConfig) -> None:
    """
    Izer build api implementation.

    Args:
        cfgs: Verified containerized backend configuration.
        
    Raises:
        IzerError: If the backend configuration has more than one model
            configuration.
        IzerError: If izer extensions do not adhere to their schema.
        IzerError: If the model file could not be found.
        IzerError: If code generation failed. 
    """
    if len(cfgs.items) > 1:
        raise IzerError('Accelerator only supoorts a single model')
    cfg = cfgs.items[0]

    output_dir = cfg.prj_info.output_path()

    # If no out_dir has been specified, use adi_cnn
    if cfg.prj_info.out_dir == Path("."):
        output_dir = output_dir / "src" / "adi_cnn"
        report_dir = Path(cfg.prj_info.name) / "src" / "adi_cnn"
    else:
        report_dir = cfg.prj_info.out_dir

    # Get the network configuration file path directly from the config
    if 'NetworkConfig' not in cfg.files:
        raise IzerError(
            "The --izer-network-config option is required for the 'izer' " \
            "backend but was not provided."
        )

    # Get Izer extensions, use default if not provided in config
    if cfg.backend.extensions is not None:
        ta = TypeAdapter(CfsaiIzerExtensions)
        try:
            izer_extensions = ta.validate_python(cfg.backend.extensions)
        except Exception as e:
            raise IzerError(
                f'config.backend "{cfg.backend}" does not appear to be a' \
                f' valid CfsaiIzerExtensions \n {e}'
            ) from e
    else:
        izer_extensions = CfsaiIzerExtensions()

    if izer_extensions.input_shape:
        _input_shape = _parse_input_shape(izer_extensions.input_shape)
    else:
        _input_shape = None

    args = CNNGeneratorArgs(
        device=cfg.target.soc, # Should be MAX7800x
        softmax=izer_extensions.softmax,
        timer=izer_extensions.timer,
        prefix=izer_extensions.prefix,
        avg_pool_rounding=izer_extensions.avg_pool_rounding,
        pipeline=izer_extensions.pipeline,
        pll=izer_extensions.pll,
        clock_divider=izer_extensions.clock_divider,
        compact_data=izer_extensions.compact_data,
        config_file=cfg.files['NetworkConfig'].as_posix() if \
            cfg.files['NetworkConfig'] else None,
        checkpoint_file=cfg.files['Model'].as_posix() \
            if cfg.files['Model'] else None,
        test_dir=output_dir.as_posix(),
        overwrite=True,
        input_shape=_input_shape,
        fifo=izer_extensions.fifo
    )
    try:
        codegen(args)
        code_path = output_dir / izer_extensions.prefix
        _convert_to_cfs(code_path, report_dir)
    except Exception as e:
        raise IzerError(str(e)) from e

if __name__ == "__main__":
    """
    If invoked directly, read VerfiedBackendConfig from a file
    and execute that.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--file', required=True, help='Config file')
    parser.add_argument('--verbose', action='store_true', help='Verbose output')
    args = parser.parse_args()

    setup_logger(debug_level=args.verbose)

    logger.debug(f"Invoking izer with: \n{args}")

    try:
        # Read JSON and parse into Pydantic model
        with open(args.file) as f:
            data = json.load(f)
            cfgs = VerifiedBackendConfig(**data)
            _build(cfgs)
    except Exception as e:
        logger.error(f'{e.__class__.__name__}{e}')
        sys.exit(1)

